[[setup]]
= Set up

[partintro]
--
This section includes information on how to setup Kibana and get it running,
including:

* Downloading
* Installing
* Starting
* Configuring
* Upgrading

[[supported-platforms]]
[float]
== Supported platforms

Packages of Kibana are provided for and tested against Linux, Darwin, and
Windows. Since Kibana runs on Node.js, we include the necessary Node.js
binaries for these platforms. Running Kibana against a separately maintained
version of Node.js is not supported.

[float]
[[elasticsearch-version]]
== HyperSec version

Kibana should be configured to run against an HyperSec node of the same
version. This is the officially supported configuration.

Running different major version releases of Kibana and HyperSec (e.g.
Kibana 5.x and HyperSec 2.x) is not supported, nor is running a minor
version of Kibana that is newer than the version of HyperSec (e.g. Kibana
5.1 and HyperSec 5.0).

Running a minor version of HyperSec that is higher than Kibana will
generally work in order to facilitate an upgrade process where HyperSec
is upgraded first (e.g. Kibana 5.0 and HyperSec 5.1). In this
configuration, a warning will be logged on Kibana server startup, so it's only
meant to be temporary until Kibana is upgraded to the same version as
HyperSec.

Running different patch version releases of Kibana and HyperSec (e.g.
Kibana 5.0.0 and HyperSec 5.0.1) is generally supported, though we
encourage users to run the same versions of Kibana and HyperSec down to
the patch version.
--

include::{kib-repo-dir}/setup/install.asciidoc[]

include::{kib-repo-dir}/setup/settings.asciidoc[]

include::{kib-repo-dir}/setup/start-stop.asciidoc[]

include::{kib-repo-dir}/setup/access.asciidoc[]

include::security/tutorials/how-to-secure-access-to-kibana.asciidoc[]

include::{kib-repo-dir}/setup/connect-to-elasticsearch.asciidoc[]

include::{kib-repo-dir}/setup/upgrade.asciidoc[]

include::{kib-repo-dir}/setup/embedding.asciidoc[]
